CREATE TABLE [dbo].[adx_rescapinter] (
    [RESOURCE_ID] NVARCHAR (50) NOT NULL,
    [START_TIME]  NVARCHAR (50) NOT NULL,
    [OFFSET]      NVARCHAR (50) NOT NULL,
    [CAP_FACTOR]  TINYINT       NOT NULL,
    [PATTERN_ID]  NVARCHAR (50) NOT NULL
);
GO

