CREATE TABLE [dbo].[adx_productlocation] (
    [PRODUCT_ID]                NVARCHAR (50)  NULL,
    [DESCRIPTION]               NVARCHAR (200) NULL,
    [LOCATION]                  NVARCHAR (50)  NULL,
    [PRODUCT_TYPE]              TINYINT        NULL,
    [RESOLUTION]                NVARCHAR (50)  NULL,
    [MIN_LOT_SIZE]              TINYINT        NULL,
    [MAX_LOT_SIZE]              SMALLINT       NULL,
    [STD_LOT_SIZE]              SMALLINT       NULL,
    [INCR_LOT_SIZE]             TINYINT        NULL,
    [BUILD_PERIOD]              NVARCHAR (50)  NULL,
    [OBSOLETE]                  NVARCHAR (50)  NULL,
    [TIME_FENCE]                NVARCHAR (50)  NULL,
    [CYCLE_TYPE]                NVARCHAR (50)  NULL,
    [CYCLE_FAMILY]              TINYINT        NULL,
    [INVENTORY]                 NVARCHAR (50)  NULL,
    [REVENUE]                   NVARCHAR (50)  NULL,
    [SHARE_FLAG]                TINYINT        NULL,
    [MIX]                       TINYINT        NULL,
    [PROD_AREA]                 NVARCHAR (50)  NULL,
    [HIER_LEVEL_1]              NVARCHAR (50)  NULL,
    [HIER_LEVEL_2]              NVARCHAR (50)  NULL,
    [HIER_LEVEL_3]              NVARCHAR (50)  NULL,
    [Product_Unit_Cost]         NVARCHAR (50)  NULL,
    [UDA_string_LOC_ID]         NVARCHAR (50)  NULL,
    [UDA_float_HOLD_COST]       NVARCHAR (50)  NULL,
    [UDA_string_PRODUCT_FAMILY] NVARCHAR (50)  NULL,
    [UDA_string_PRODUCT_GROUP]  NVARCHAR (50)  NULL,
    [UDA_string_TECHNOLOGY]     NVARCHAR (50)  NULL,
    [UDA_string_PACKAGE]        NVARCHAR (50)  NULL,
    [UDA_string_SHARED]         NVARCHAR (50)  NULL,
    [UDA_string_FAB_LOC]        NVARCHAR (50)  NULL,
    [UDA_string_MASK_LAYERS]    NVARCHAR (50)  NULL,
    [UDA_string_WAFER_SIZE]     NVARCHAR (50)  NULL,
    [UDA_string_BUMP_LOC]       NVARCHAR (50)  NULL,
    [UDA_string_BUMP_TYPE]      NVARCHAR (50)  NULL,
    [UDA_string_PROBE_LOC]      NVARCHAR (50)  NULL,
    [UDA_string_PACKAGE_FAMILY] NVARCHAR (50)  NULL,
    [UDA_string_ASSY_LOC]       NVARCHAR (50)  NULL,
    [UDA_string_TEST_LOC]       NVARCHAR (50)  NULL,
    [UDA_string_A_MAT_STATUS]   NVARCHAR (50)  NULL,
    [c]                         INT            NULL,
    [PROD_SKU_ID]               NVARCHAR (50)  NULL,
    [LOCATION_ID]               NVARCHAR (50)  NULL,
    [CYCLE_TIME_TYPE]           NVARCHAR (50)  NULL,
    [CYCLE_TIME_FAMILY]         TINYINT        NULL,
    [TECHNOLOGY]                NVARCHAR (50)  NULL
);
GO

ALTER TABLE [dbo].[adx_productlocation]
    ADD CONSTRAINT [DEFAULT_adx_productlocation_c] DEFAULT ((1)) FOR [c];
GO

