CREATE TABLE [dbo].[adx_productlocation] (
    [PRODUCT_ID]                NVARCHAR (50)  NOT NULL,
    [DESCRIPTION]               NVARCHAR (200) NOT NULL,
    [LOCATION]                  NVARCHAR (50)  NOT NULL,
    [PRODUCT_TYPE]              TINYINT        NOT NULL,
    [RESOLUTION]                NVARCHAR (50)  NOT NULL,
    [MIN_LOT_SIZE]              TINYINT        NOT NULL,
    [MAX_LOT_SIZE]              SMALLINT       NOT NULL,
    [STD_LOT_SIZE]              SMALLINT       NOT NULL,
    [INCR_LOT_SIZE]             TINYINT        NOT NULL,
    [BUILD_PERIOD]              NVARCHAR (50)  NOT NULL,
    [OBSOLETE]                  NVARCHAR (50)  NOT NULL,
    [TIME_FENCE]                NVARCHAR (50)  NOT NULL,
    [CYCLE_TYPE]                NVARCHAR (50)  NOT NULL,
    [CYCLE_FAMILY]              TINYINT        NOT NULL,
    [INVENTORY]                 NVARCHAR (50)  NOT NULL,
    [REVENUE]                   NVARCHAR (50)  NOT NULL,
    [SHARE_FLAG]                TINYINT        NOT NULL,
    [MIX]                       TINYINT        NOT NULL,
    [PROD_AREA]                 NVARCHAR (50)  NOT NULL,
    [HIER_LEVEL_1]              NVARCHAR (50)  NOT NULL,
    [HIER_LEVEL_2]              NVARCHAR (50)  NOT NULL,
    [HIER_LEVEL_3]              NVARCHAR (50)  NOT NULL,
    [Product_Unit_Cost]         NVARCHAR (50)  NOT NULL,
    [UDA_string_LOC_ID]         NVARCHAR (50)  NOT NULL,
    [UDA_float_HOLD_COST]       NVARCHAR (50)  NOT NULL,
    [UDA_string_PRODUCT_FAMILY] NVARCHAR (50)  NOT NULL,
    [UDA_string_PRODUCT_GROUP]  NVARCHAR (50)  NOT NULL,
    [UDA_string_TECHNOLOGY]     NVARCHAR (50)  NOT NULL,
    [UDA_string_PACKAGE]        NVARCHAR (50)  NOT NULL,
    [UDA_string_SHARED]         NVARCHAR (50)  NOT NULL,
    [UDA_string_FAB_LOC]        NVARCHAR (50)  NOT NULL,
    [UDA_string_MASK_LAYERS]    NVARCHAR (50)  NOT NULL,
    [UDA_string_WAFER_SIZE]     NVARCHAR (50)  NOT NULL,
    [UDA_string_BUMP_LOC]       NVARCHAR (50)  NOT NULL,
    [UDA_string_BUMP_TYPE]      NVARCHAR (50)  NOT NULL,
    [UDA_string_PROBE_LOC]      NVARCHAR (50)  NOT NULL,
    [UDA_string_PACKAGE_FAMILY] NVARCHAR (50)  NOT NULL,
    [UDA_string_ASSY_LOC]       NVARCHAR (50)  NOT NULL,
    [UDA_string_TEST_LOC]       NVARCHAR (50)  NOT NULL,
    [UDA_string_A_MAT_STATUS]   NVARCHAR (50)  NOT NULL
);
GO

