CREATE TABLE [dbo].[adx_vendor] (
    [VENDOR_ID]           NVARCHAR (50) NULL,
    [VENDOR_DESCRIPTION]  NVARCHAR (50) NULL,
    [VENDOR_HIER_LEVEL_1] NVARCHAR (50) NULL,
    [VENDOR_HIER_LEVEL_2] NVARCHAR (50) NULL,
    [VENDOR_HIER_LEVEL_3] NVARCHAR (50) NULL,
    [VENDOR_TYPE]         NVARCHAR (50) NULL
);
GO

