CREATE TABLE [dbo].[adx_route] (
    [PRODAREA]     NVARCHAR (50) NOT NULL,
    [ROUTE_ID]     NVARCHAR (50) NOT NULL,
    [SEGMENT_ID]   NVARCHAR (50) NOT NULL,
    [SEGMENT_IX]   TINYINT       NOT NULL,
    [STEP_IX]      TINYINT       NOT NULL,
    [OPERATION_ID] NVARCHAR (50) NOT NULL
);
GO

