CREATE TABLE [dbo].[adx_product] (
    [PRODUCT_ID]           NVARCHAR (50) NULL,
    [DESCRIPTION]          NVARCHAR (50) NULL,
    [PRODUCT_TYPE]         NVARCHAR (50) NULL,
    [PRODAREA]             NVARCHAR (50) NULL,
    [HIER_LEVEL_1]         NVARCHAR (50) NULL,
    [HIER_LEVEL_2]         NVARCHAR (50) NULL,
    [HIER_LEVEL_3]         NVARCHAR (50) NULL,
    [FG_HIER_LEVEL_1]      NVARCHAR (50) NULL,
    [FG_HIER_LEVEL_2]      NVARCHAR (50) NULL,
    [FG_HIER_LEVEL_3]      NVARCHAR (50) NULL,
    [END_ITEM]             NVARCHAR (50) NULL,
    [DP_COMP]              NVARCHAR (50) NULL,
    [FG_COMP]              NVARCHAR (50) NULL,
    [VIRTUAL]              NVARCHAR (50) NULL,
    [DP_COMP_KEY]          NVARCHAR (50) NULL,
    [FG_COMP_KEY]          NVARCHAR (50) NULL,
    [VIRTUAL_KEY]          NVARCHAR (50) NULL,
    [A_MAT_STATUS]         NVARCHAR (50) NULL,
    [LATE_FORECAST]        NVARCHAR (50) NULL,
    [LATE_SALES]           NVARCHAR (50) NULL,
    [PROD_SKU_ID]          NVARCHAR (50) NULL,
    [PROD_SKU_DESCRIPTION] NVARCHAR (50) NULL
);
GO

