CREATE TABLE [dbo].[adx_operation] (
    [OPERATION_ID]         NVARCHAR (50) NULL,
    [DESCRIPTION]          NVARCHAR (50) NULL,
    [MIN_WAIT_TIME]        NVARCHAR (50) NULL,
    [MAX_WAIT_TIME]        NVARCHAR (50) NULL,
    [DEFAULT_SETUP_TIME]   NVARCHAR (50) NULL,
    [FIRST_BATCH_TIME]     NVARCHAR (50) NULL,
    [FIRST_UNIT_TIME]      NVARCHAR (50) NULL,
    [UPH]                  NVARCHAR (50) NULL,
    [POST_PROCESSING_TIME] NVARCHAR (50) NULL,
    [BATCH_SCALE_FACTOR]   NVARCHAR (50) NULL,
    [YIELD_FACTOR]         TINYINT       NULL,
    [YIELD_LOST_QTY]       NVARCHAR (50) NULL,
    [BORA_ID]              NVARCHAR (50) NULL,
    [SETUP_TYPE]           NVARCHAR (50) NULL,
    [PROCESS_TYPE]         NVARCHAR (50) NULL,
    [CAPABLE_TYPE]         NVARCHAR (50) NULL,
    [TRANSFER_LOT_SIZE]    NVARCHAR (50) NULL
);
GO

