CREATE TABLE [dbo].[adx_product] (
    [PRODUCT_ID]      NVARCHAR (50) NOT NULL,
    [DESCRIPTION]     NVARCHAR (50) NOT NULL,
    [PRODUCT_TYPE]    NVARCHAR (50) NOT NULL,
    [PRODAREA]        NVARCHAR (50) NULL,
    [HIER_LEVEL_1]    NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_2]    NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_3]    NVARCHAR (50) NOT NULL,
    [FG_HIER_LEVEL_1] NVARCHAR (50) NOT NULL,
    [FG_HIER_LEVEL_2] NVARCHAR (50) NOT NULL,
    [FG_HIER_LEVEL_3] NVARCHAR (50) NOT NULL,
    [END_ITEM]        NVARCHAR (50) NOT NULL,
    [A_MAT_STATUS]    NVARCHAR (50) NOT NULL,
    [LATE_FORECAST]   NVARCHAR (50) NOT NULL,
    [LATE_SALES]      NVARCHAR (50) NOT NULL
);
GO

