CREATE TABLE [dbo].[ADX_GREYBOX_HEADER] (
    [MODEL_ID]            NVARCHAR (100) NULL,
    [CONSTRAINT_ID]       NVARCHAR (255) NULL,
    [BUILD_POLICY]        NVARCHAR (255) NULL,
    [DEFAULT_BUILD_AHEAD] NVARCHAR (255) NULL,
    [BUILD_AHEAD_NAME]    NVARCHAR (255) NULL,
    [WEIGHT_FACTOR_NAME]  NVARCHAR (255) NULL,
    [HIER_LEVEL_1]        NVARCHAR (255) NULL,
    [HIER_LEVEL_2]        NVARCHAR (255) NULL,
    [HIER_LEVEL_3]        NVARCHAR (255) NULL,
    [GROUP1]              NVARCHAR (255) NULL,
    [GROUP2]              NVARCHAR (255) NULL,
    [DATA_LAST_UPDATED]   NVARCHAR (50)  NULL
);
GO

