CREATE TABLE [dbo].[adx_resource] (
    [RESOURCE_ID]      NVARCHAR (50) NOT NULL,
    [DESCRIPTION]      NVARCHAR (50) NOT NULL,
    [LOCATION]         NVARCHAR (50) NOT NULL,
    [RES_TYPE]         NVARCHAR (50) NOT NULL,
    [BATCH_PERIOD]     NVARCHAR (50) NOT NULL,
    [BATCH_TYPE]       NVARCHAR (50) NOT NULL,
    [AVG_BATCH_VOLUME] NVARCHAR (50) NOT NULL,
    [MIN_BATCH_VOLUME] NVARCHAR (50) NOT NULL,
    [MAX_BATCH_VOLUME] NVARCHAR (50) NOT NULL,
    [SPEED_FACTOR]     NVARCHAR (50) NOT NULL,
    [MULTI_RES_FACTOR] NVARCHAR (50) NOT NULL,
    [CARE]             TINYINT       NOT NULL,
    [DELAY_ALLOWED]    NVARCHAR (50) NOT NULL,
    [PERIOD_MGR_ID]    NVARCHAR (50) NOT NULL,
    [SETUP_MATRIX_ID]  NVARCHAR (50) NOT NULL,
    [CAPABLE_TYPE]     NVARCHAR (50) NOT NULL,
    [MIX_TYPE]         NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_1]     NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_2]     NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_3]     NVARCHAR (50) NOT NULL,
    [OpOverrideType]   NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_3_bak] NVARCHAR (50) NOT NULL,
    [HIER_LEVEL_1_bak] NVARCHAR (50) NOT NULL
);
GO

