CREATE TABLE [dbo].[adx_workorder] (
    [LOT_ID]              NVARCHAR (50) NULL,
    [COMMODITY]           NVARCHAR (50) NULL,
    [LOCATION]            NVARCHAR (50) NULL,
    [STATUS]              NVARCHAR (50) NULL,
    [DUE_DATE]            DATE          NULL,
    [QUANTITY]            INT           NULL,
    [COST]                INT           NULL,
    [OpOverrideType]      NVARCHAR (50) NULL,
    [ASSY_LOC]            NVARCHAR (50) NULL,
    [GRADE_DECOMPOSITION] NVARCHAR (50) NULL,
    [FAB_LOC]             NVARCHAR (50) NULL,
    [WIRE_COLOR]          NVARCHAR (50) NULL,
    [ALLOCATION]          NVARCHAR (50) NULL,
    [WAFER_LOT]           NVARCHAR (50) NULL,
    [TECHNOLOGY]          NVARCHAR (50) NULL,
    [MASK_LAYERS]         NVARCHAR (50) NULL,
    [WAFER_SIZE]          NVARCHAR (50) NULL,
    [MAT_TYPE]            NVARCHAR (50) NULL,
    [PASSIVATION]         NVARCHAR (50) NULL,
    [BUMP_LOC]            NVARCHAR (50) NULL,
    [BUMP_TYPE]           NVARCHAR (50) NULL,
    [PROBE_LOC]           NVARCHAR (50) NULL,
    [DB_LOC]              NVARCHAR (50) NULL,
    [PACKAGE_FAMILY]      NVARCHAR (50) NULL,
    [PACKAGE]             NVARCHAR (50) NULL,
    [TEST_LOC]            NVARCHAR (50) NULL
);
GO

