CREATE TABLE [dbo].[adx_safety_stock] (
    [PRODUCT_ID]   NVARCHAR (50) NULL,
    [LOCATION_ID]  NVARCHAR (50) NULL,
    [START_DATE]   NVARCHAR (50) NULL,
    [END_DATE]     NVARCHAR (50) NULL,
    [SAFETY_LEVEL] NVARCHAR (50) NULL,
    [SAFETY_POC]   NVARCHAR (50) NULL,
    [PENALTY_100]  NVARCHAR (50) NULL,
    [PENALTY_80]   NVARCHAR (50) NULL,
    [PENALTY_50]   NVARCHAR (50) NULL
);
GO

