CREATE TABLE [dbo].[adx_route] (
    [PRODAREA]     NVARCHAR (50) NULL,
    [ROUTE_ID]     NVARCHAR (50) NULL,
    [SEGMENT_ID]   NVARCHAR (50) NULL,
    [SEGMENT_IX]   TINYINT       NULL,
    [STEP_IX]      TINYINT       NULL,
    [OPERATION_ID] NVARCHAR (50) NULL
);
GO

