CREATE TABLE [dbo].[ADX_GREYBOX_TARGET] (
    [MODEL_ID]          NVARCHAR (100) NULL,
    [CONSTRAINT_ID]     NVARCHAR (255) NULL,
    [CSTR_OBJECT_NAME]  NVARCHAR (255) NULL,
    [UDA_NAME]          NVARCHAR (255) NULL,
    [CONSTRAINT_TYPE]   NVARCHAR (255) NULL,
    [RESTRICTION_VALUE] NVARCHAR (255) NULL,
    [CONSTRAINT_ORDER]  NVARCHAR (255) NULL,
    [DATA_LAST_UPDATED] NVARCHAR (50)  NULL
);
GO

