CREATE TABLE [dbo].[adx_op_override] (
    [OPERATION_ID]             NVARCHAR (50) NOT NULL,
    [PRODUCT_ID]               NVARCHAR (50) NOT NULL,
    [RESOURCE_ID]              NVARCHAR (50) NOT NULL,
    [START_DATE]               NVARCHAR (50) NOT NULL,
    [END_DATE]                 NVARCHAR (50) NOT NULL,
    [MIN_WAIT_TIME]            NVARCHAR (50) NOT NULL,
    [MAX_WAIT_TIME]            NVARCHAR (50) NOT NULL,
    [DEFAULT_SETUP_TIME]       NVARCHAR (50) NOT NULL,
    [PROCESS_TIME_FIRST_BATCH] NVARCHAR (50) NOT NULL,
    [PROCESS_TIME_FIRST_UNIT]  NVARCHAR (50) NOT NULL,
    [UPH]                      NVARCHAR (50) NOT NULL,
    [POST_PROCESSING_TIME]     NVARCHAR (50) NULL,
    [BATCH_SCALE_FACTOR]       NVARCHAR (50) NOT NULL,
    [YIELD_FACTOR]             NVARCHAR (50) NOT NULL,
    [YIELD_LOST_QTY]           NVARCHAR (50) NOT NULL,
    [BORA_ID]                  NVARCHAR (50) NOT NULL,
    [SETUP_TYPE]               NVARCHAR (50) NOT NULL,
    [PROCESS_TYPE]             NVARCHAR (50) NOT NULL,
    [CAPABLE_TYPE]             NVARCHAR (50) NOT NULL,
    [TRANSFER_LOT_SIZE]        NVARCHAR (50) NOT NULL
);
GO

