CREATE TABLE [dbo].[adx_customer] (
    [CUSTOMER_ID]           NVARCHAR (50) NULL,
    [CUSTOMER_DESCRIPTION]  NVARCHAR (50) NULL,
    [CustomerPref]          TINYINT       NULL,
    [CUSTOMER_HIER_LEVEL_1] NVARCHAR (50) NULL,
    [CUSTOMER_HIER_LEVEL_2] NVARCHAR (50) NULL,
    [CUSTOMER_HIER_LEVEL_3] NVARCHAR (50) NULL
);
GO

