CREATE TABLE [dbo].[cappattern] (
    [CAP_PATTERN_ID] NVARCHAR (50) NOT NULL,
    [IDX]            NVARCHAR (50) NOT NULL,
    [DURATION]       NVARCHAR (50) NOT NULL,
    [QUANTITY]       NVARCHAR (50) NOT NULL
);
GO

