CREATE TABLE [dbo].[POC_delivery] (
    [类]                  SMALLINT      NOT NULL,
    [交货]                 INT           NOT NULL,
    [项目]                 TINYINT       NOT NULL,
    [类别]                 NVARCHAR (50) NOT NULL,
    [创建者]                NVARCHAR (50) NOT NULL,
    [时间]                 NVARCHAR (50) NOT NULL,
    [创建日期]               NVARCHAR (50) NOT NULL,
    [PN]                 NVARCHAR (50) NOT NULL,
    [已输入物料]              NVARCHAR (50) NOT NULL,
    [物料组]                SMALLINT      NOT NULL,
    [Plant]              NVARCHAR (50) NOT NULL,
    [Storage]            SMALLINT      NOT NULL,
    [批次]                 NVARCHAR (1)  NULL,
    [供应商批次]              NVARCHAR (1)  NULL,
    [客户物料号]              NVARCHAR (50) NOT NULL,
    [产品模式]               NVARCHAR (50) NULL,
    [Quantity_Delivered] FLOAT (53)    NOT NULL,
    [计]                  NVARCHAR (50) NOT NULL,
    [SU]                 NVARCHAR (50) NOT NULL,
    [分子]                 TINYINT       NOT NULL,
    [分母]                 TINYINT       NOT NULL,
    [净重量]                FLOAT (53)    NOT NULL,
    [毛重]                 FLOAT (53)    NOT NULL,
    [WUn]                NVARCHAR (50) NOT NULL,
    [业务量]                FLOAT (53)    NOT NULL,
    [VUn]                NVARCHAR (1)  NULL,
    [PD]                 NVARCHAR (1)  NULL,
    [无限制]                NVARCHAR (1)  NULL,
    [过量交货限度]             FLOAT (53)    NOT NULL,
    [交货不足限度]             FLOAT (53)    NOT NULL,
    [BS]                 NVARCHAR (1)  NULL,
    [冻结]                 NVARCHAR (1)  NULL,
    [Mat_Av_Dt]          NVARCHAR (50) NOT NULL,
    [Quantity]           FLOAT (53)    NOT NULL,
    [Description]        NVARCHAR (50) NOT NULL,
    [仓位]                 NVARCHAR (1)  NULL,
    [起始凭证]               NVARCHAR (1)  NULL,
    [项目2]                TINYINT       NOT NULL,
    [凭证]                 NVARCHAR (1)  NULL,
    [PrDocLogSys]        NVARCHAR (1)  NULL,
    [参考凭证]               INT           NOT NULL,
    [参考项]                SMALLINT      NOT NULL,
    [U]                  NVARCHAR (50) NOT NULL,
    [上层项]                TINYINT       NOT NULL,
    [BilRl]              NVARCHAR (50) NULL,
    [LGrp]               TINYINT       NOT NULL,
    [运输组]                TINYINT       NOT NULL
);
GO

