CREATE TABLE [dbo].[SO_03222024] (
    [Creation_Date]      DATE           NOT NULL,
    [Sales_Channel]      NVARCHAR (50)  NOT NULL,
    [订单类型描述]             NVARCHAR (50)  NOT NULL,
    [CustomerCode]       NVARCHAR (50)  NOT NULL,
    [CustomerName]       NVARCHAR (50)  NOT NULL,
    [注释]                 NVARCHAR (50)  NULL,
    [Series]             NVARCHAR (50)  NOT NULL,
    [PN]                 NVARCHAR (50)  NOT NULL,
    [Model]              NVARCHAR (100) NULL,
    [Description]        NVARCHAR (50)  NOT NULL,
    [物料组2描述]             NVARCHAR (50)  NOT NULL,
    [物料组3描述]             NVARCHAR (1)   NULL,
    [物料短描述]              NVARCHAR (50)  NOT NULL,
    [DeliveryDate0]      NVARCHAR (50)  NULL,
    [DeliveryQuantity]   NVARCHAR (50)  NOT NULL,
    [Revenue]            NVARCHAR (50)  NOT NULL,
    [UnmetQuantity]      NVARCHAR (50)  NOT NULL,
    [SONumber]           NVARCHAR (50)  NOT NULL,
    [CompanyCode]        SMALLINT       NOT NULL,
    [SystemSONumber]     NVARCHAR (50)  NOT NULL,
    [ItemId]             SMALLINT       NOT NULL,
    [CompanyName]        NVARCHAR (50)  NOT NULL,
    [IndustrialStandard] NVARCHAR (50)  NOT NULL,
    [CustomerPN]         NVARCHAR (50)  NOT NULL,
    [Quantity]           NVARCHAR (50)  NOT NULL,
    [Currency]           NVARCHAR (50)  NOT NULL,
    [DeliveryDate]       NVARCHAR (50)  NOT NULL,
    [销售员姓名]              NVARCHAR (50)  NOT NULL,
    [拒绝原因描述]             NVARCHAR (1)   NULL,
    [创建人]                NVARCHAR (50)  NOT NULL
);
GO

