CREATE TABLE [dbo].[uda] (
    [USER_CLASS_ID] NVARCHAR (50) NOT NULL,
    [USER_NAME]     NVARCHAR (50) NOT NULL,
    [USER_TYPE]     NVARCHAR (50) NOT NULL,
    [USER_DESC]     NVARCHAR (50) NULL
);
GO

